AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  flickr-cron

  Sample SAM Template for flickr-cron

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:
  FlickrGetMostInterestingImages:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: flickr-cron/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          FLICKR_API_KEY: db2d5cf130abcefd53a77275be72dbff

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  FlickrGetMostInterestingImagesApi:
    Description: API Gateway endpoint URL for Prod stage for FlickrGetMostInterestingImages function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FlickrGetMostInterestingImagesFunction:
    Description: FlickrGetMostInterestingImages Lambda Function ARN
    Value: !GetAtt FlickrGetMostInterestingImages.Arn
  FlickrGetMostInterestingImagesFunctionIamRole:
    Description: Implicit IAM Role created for FlickrGetMostInterestingImages function
    Value: !GetAtt FlickrGetMostInterestingImagesRole.Arn

